### ISSUE TITLE
Missing installation instruction step

### ISSUE THREAD

**Issue by doisyg** [RobotecAI/RGLGazeboPlugin#10]
Hello,
Nice to see a new GPU lidar competitor, I am trying to give it a spin to evaluate it. I followed the instructions for using the gazebo plugin library, i.e. dowloaded the 3 libs from the release and added them the gazebo paths, but I get the following errors when trying `ign gazebo rgl_playground.sdf `:

> Error while loading the library [/home/gd/Downloads/libRGLServerPluginManager.so]: libRobotecGPULidar.so: cannot open shared object file: No such file or directory
> [Err] [SystemLoader.cc:87] Failed to load system plugin [RGLServerPluginManager] : couldn't load library on path [/home/gd/Downloads/libRGLServerPluginManager.so].
> Error while loading the library [/home/gd/Downloads/libRGLServerPluginInstance.so]: libRobotecGPULidar.so: cannot open shared object file: No such file or directory
> [Err] [SystemLoader.cc:87] Failed to load system plugin [RGLServerPluginInstance] : couldn't load library on path [/home/gd/Downloads/libRGLServerPluginInstance.so].
> 

I guess `libRobotecGPULidar.so` is needed too (from https://github.com/RobotecAI/RobotecGPULidar/releases ?), where should it be installed ?

**Comment by prybicki** [comment]
Hello @doisyg 
Thank you a lot for your report :tada:
There's indeed a bug in the pre-built libraries.
I prepared a shell script that should fix the problem for you.
We will also soon make a new release fixing this issue.

_Note: you will need the following dependency to execute the following script:_ `sudo apt install chrpath`

```bash
cd
mkdir GazeboPlugins
cd GazeboPlugins
wget https://github.com/RobotecAI/RGLGazeboPlugin/releases/download/v0.1.0/libRGLServerPluginInstance.so
wget https://github.com/RobotecAI/RGLGazeboPlugin/releases/download/v0.1.0/libRGLServerPluginManager.so
wget https://github.com/RobotecAI/RGLGazeboPlugin/releases/download/v0.1.0/libRGLVisualize.so
wget https://github.com/RobotecAI/RobotecGPULidar/releases/download/v0.11.3/libRobotecGPULidar.so
chrpath -r /home/${USER}/GazeboPlugins libRGLServerPluginInstance.so
chrpath -r /home/${USER}/GazeboPlugins libRGLServerPluginManager.so
export IGN_GUI_PLUGIN_PATH=/home/${USER}/GazeboPlugins
export IGN_GAZEBO_SYSTEM_PLUGIN_PATH=/home/${USER}/GazeboPlugins
```
Please let me know if it works for you.

**Comment by msz-rai** [comment]
Hello @doisyg 
Thank you again for reporting the issue.
I have prepared a new [release](https://github.com/RobotecAI/RGLGazeboPlugin/releases/tag/v0.1.1) that fixes RobotecGPULidar linking problem. Also, I have updated [the installation instructions](https://github.com/RobotecAI/RGLGazeboPlugin/tree/v0.1.1#installation).

Please let me ask you to test it.

**Comment by doisyg** [comment]
> Hello @doisyg Thank you again for reporting the issue. I have prepared a new [release](https://github.com/RobotecAI/RGLGazeboPlugin/releases/tag/v0.1.1) that fixes RobotecGPULidar linking problem. Also, I have updated [the installation instructions](https://github.com/RobotecAI/RGLGazeboPlugin/tree/v0.1.1#installation).
> 
> Please let me ask you to test it.

Now getting the following:

> Error while loading the library [/home/gd/Downloads/libRGLServerPluginManager.so]: libprotobuf.so.17: cannot open shared object file: No such file or directory
> [Err] [SystemLoader.cc:87] Failed to load system plugin [RGLServerPluginManager] : couldn't load library on path [/home/gd/Downloads/libRGLServerPluginManager.so].
> Error while loading the library [/home/gd/Downloads/libRGLServerPluginInstance.so]: libprotobuf.so.17: cannot open shared object file: No such file or directory
> [Err] [SystemLoader.cc:87] Failed to load system plugin [RGLServerPluginInstance] : couldn't load library on path [/home/gd/Downloads/libRGLServerPluginInstance.so].
> ../src/intel/isl/isl.c:2216: FINISHME: ../src/intel/isl/isl.c:isl_surf_supports_ccs: CCS for 3D textures is disabled, but a workaround is available.

I am on Ubuntu 22.04, I bet libprotobuf.so.17 is 20.04 version

**Comment by msz-rai** [comment]
Thank you for the test.
It seems that Ubuntu 20 and Ubuntu 22 need separate binaries. I have updated the [release](https://github.com/RobotecAI/RGLGazeboPlugin/releases/tag/v0.1.1).

**Comment by doisyg** [comment]
New error : 

$ ign gazebo rgl_playground.sdf 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
[Tue Apr 4 09:12:25 2023]: Logging configured: level=info, file=(disabled), stdout=true
[09:12:25][     9 us][info]: RGL Version 0.11.3 branch=stable commitSHA1=e5ea8a1a74c253a304f4d1d4652391bca9d448e6
[09:12:25][ 27450 us][info]: Running on GPU: NVIDIA GeForce RTX 3050 Ti Laptop GPU
[09:12:25][    13 us][info]: Built against OptiX SDK version: 7.2.0
[09:12:25][     0 us][info]: Built against OptiX ABI version: 41
[09:12:25][     0 us][info]: Built against CUDA Toolkit version: 11.2
[09:12:25][     3 us][info]: Installed CUDA runtime version: 11.2
[09:12:25][     0 us][info]: Installed CUDA driver version: 12.0
[09:12:25][ 23622 us][info]: Installed NVidia kernel driver version: 525.105.17
[Tue Apr 4 09:12:26 2023]: Logging configured: level=error, file=(disabled), stdout=true
**[Err] [LidarPatternLoader.cc:219] failed to open file '"/home/mateusz/RGLGazeboPlugin/RGLServerPlugin/lidar_patterns/VelodyneVLS128.mat3x4f"' or file is empty, data will not be loaded.**
[Err] [LidarPatternLoader.cc:193] Failed to load preset.
[Err] [LidarPatternLoader.cc:54] Failed to load lidar pattern. See plugin's documentation for available options.

**Comment by msz-rai** [comment]
Thank you for finding the next bug (hopefully the last one).
The plugin's compilation made the path to `lidar_patterns` directory hard-coded. This way, presets didn't work on pre-built release binaries on a different machine than mine.

I have released [a new patch](https://github.com/RobotecAI/RGLGazeboPlugin/releases/tag/v0.1.2) to fix this problem. Please follow the updated [demo instructions](https://github.com/RobotecAI/RGLGazeboPlugin#demo).

**Comment by doisyg** [comment]
Working now!
