### ISSUE TITLE
Request for Ignition Garden Support

### ISSUE THREAD

**Issue by namanmalik-ari** [RobotecAI/RGLGazeboPlugin#14]
### Environment 

- Ubuntu 22.04
- Ignition Garden

### Description

Hi, I am using Ignition Garden for a project and I wanted to use the RGLGazeboPlugin in the same project but I am unable to do so since the support for plugin is limited to Ignition Fortress only.

I tried to build the project anyway but failed to do so throwing this error.
![image](https://user-images.githubusercontent.com/123245840/233759096-4bec2aa3-eb68-466a-bf1e-fdffae723de3.png)

Just by looking at the error it seems like it's trying to find gazebo6 so is it possible to change the dependencies to Garden by just modifying some config files.
I'm a bit new to build gazebo plugins so could anyone help me porting this to ignition garden or guide me through the process

**Comment by adamdbrw** [comment]
@namanmalik-ari if you are willing to give it a try and port the plugin that would be awesome. We are certainly no expert in the matter and I cannot guarantee that we will find a bandwidth to solve this issue before you need it. What we can do is certainly support you on the RGL side and review the work.

**Comment by prybicki** [comment]
@namanmalik-ari 
We would certainly love to support Ignition Garden, however, at the moment, we don't have the capacity to focus on this task.
I will keep the issue open so that we can come back to this topic later.

**Comment by namanmalik-ari** [comment]
@adamdbrw @prybicki I have added support for Gazebo Garden as mention in issue -> #18.
I have tested it out with `gz-sim7.5.0` on `ubuntu22.04`. 
Please have a look and let me know if any changes are required.
I currently have created a pull request to main and it is showing some merge conflicts since there have been some updates from your end. Once you are verified with the results. I request you to please create another branch with commit at `539742c7afc650cfea5abfa78505ce3c1b1e42df`.

**Comment by msz-rai** [comment]
@namanmalik-ari 
Thank you for your migration to Gazebo Garden. PR has already been merged into the [garden](https://github.com/RobotecAI/RGLGazeboPlugin/tree/garden) branch.
