### ISSUE TITLE
Gazebo Harmonic Support 

### ISSUE THREAD

**Issue by Wiktor-99** [RobotecAI/RGLGazeboPlugin#33]
## Description
Hello, 
As Gazebo Harmonic is a LTS version, it would be beneficial to have the RGLGazeboPlugin version compatible with Harmonic. 
I have already submitted a pull request for this, you can find it here: [PR#32](https://github.com/RobotecAI/RGLGazeboPlugin/pull/32).

**Comment by msz-rai** [comment]
Hello @Wiktor-99 
Thank you for your contribution.
We will take a look and test it as soon as we close our ongoing topics. Harmonic support is surely what we and the community would benefit from.
