### ISSUE TITLE
Point Cloud Message row_step is 0

### ISSUE THREAD

**Issue by jasmeet0915** [RobotecAI/RGLGazeboPlugin#46]
Hello, I was working with the RGLGazebo Plugin when I noticed that the PointCloudMsg had a 0 row_step value as it was not being set in [CreatePointCloudMsg()](https://github.com/RobotecAI/RGLGazeboPlugin/blob/44b4be88e0e1a7a9267c0e3563be2f316f7d2d95/RGLServerPlugin/src/Lidar.cc#L281).

The change is quite small and I have already added the fix as a PR to this repo: https://github.com/RobotecAI/RGLGazeboPlugin/pull/47

**Comment by msz-rai** [comment]
Thank you for the fix.
I've tested it and already merged PR.
